# Generated by Django 5.2.5 on 2026-09-13 11:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_id', models.CharField(default=core.models.make_registered_id, editable=False, max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('role', models.CharField(choices=[('farmer', 'Farmer / FPO'), ('consumer', 'Consumer'), ('bulk', 'Bulk Buyer'), ('delivery', 'Delivery Partner'), ('admin', 'Admin')], default='consumer', max_length=20)),
                ('password_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
